version: '3'

services:
  fuse-dev:
    build:
      context: .
      dockerfile: src/fuse-driver/docker/Dockerfile.runtime
    privileged: true  # Needed for FUSE
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    security_opt:
      - apparmor:unconfined
    volumes:
      # Storage volume (controlled by USE_HOST_STORAGE env var)
      # For testing/development, USE_HOST_STORAGE=false uses container internal storage
      - type: bind
        source: ${DEV_HOST_STORAGE_PATH:-./nas-storage}
        target: ${NAS_STORAGE_PATH:-/var/nas-storage}
        bind:
          create_host_path: true
    env_file:
      - .env
    environment:
      - NAS_MOUNT_POINT=${NAS_MOUNT_POINT:-/mnt/nas-mount}
      - NAS_STORAGE_PATH=${NAS_STORAGE_PATH:-/var/nas-storage}
      - NAS_LOG_FILE=${NAS_LOG_FILE:-/var/log/nas-emu.log}
      - NAS_LOG_LEVEL=${NAS_LOG_LEVEL:-2}
      - SMB_SHARE_NAME=${SMB_SHARE_NAME:-nasshare}
      - SMB_USERNAME=${SMB_USERNAME:-nasusr}
      - SMB_PASSWORD=${SMB_PASSWORD:-naspass}
      - CONFIG_FILE=${CONFIG_FILE:-no_faults.conf}
      - USE_HOST_STORAGE=${USE_HOST_STORAGE:-true}
    ports:
      - "${NAS_SMB_PORT:-1445}:445"   # SMB port for Samba server
    # Let entrypoint handle everything
    # No command override needed - use default from Dockerfile

volumes:
  # Keep the fuse-data volume for compatibility, but don't use it in the mounts
  fuse-data: